name: Build and upload
on: 
  push:
    branches: [main, staging, 'update-versions']
  workflow_dispatch:
    branches: [main, staging, 'update-versions']
  schedule:
  - cron: "39 6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Fetch external data
      env:
        google_service_private_key: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY }}
        google_service_private_key_id: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY_ID }}
        JEKYLL_ENV: production 
        LC_ALL: "C.UTF-8"
        LANG: "en_US.UTF-8"
        LANGUAGE: "en_US.UTF-8" 
      run: _bin/build.sh
    - name: Deploy site
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        OVH_PRIVATE: ${{ secrets.OVH_PRIVATE }}
        WEBHOST_OVH: ${{ secrets.WEBHOST_OVH }}
      run: _bin/deploy.sh
